# Generated by Django 2.0.9 on 2018-12-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181210_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cust_id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
