# Generated by Django 2.0.9 on 2018-12-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20181210_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cust_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Customer'),
            preserve_default=False,
        ),
    ]
