# Generated by Django 2.0.9 on 2018-12-10 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_order_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='blog.Customer'),
        ),
    ]
