# Generated by Django 2.0.9 on 2018-12-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='picture',
            field=models.ImageField(upload_to='good_detail/%y%m%d'),
        ),
    ]
