# Generated by Django 2.0.9 on 2018-12-10 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20181210_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='picture',
        ),
    ]
