# Generated by Django 2.0.9 on 2018-12-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_good_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='customer_holder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='blog.Order'),
        ),
    ]
