# Generated by Django 2.0.9 on 2018-12-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_good_customer_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='customer_holder',
        ),
    ]
