# Generated by Django 2.0.9 on 2018-12-11 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_good_customer_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='holder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='blog.Customer'),
        ),
    ]
